######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 31 18:34:39 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += addressbook.h
SOURCES += addressbook.cpp main.cpp
