######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 29 12:56:43 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cellstate.h grid.h gridcell.h gridwindow.h utility.h
SOURCES += gridcell.cpp gridwindow.cpp main.cpp utility.cpp
