######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 5 12:53:59 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h previewer.h
FORMS += previewer.ui
SOURCES += main.cpp mainwindow.cpp previewer.cpp
