######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 5 21:05:49 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += radiobuttons.h
SOURCES += main.cpp radiobuttons.cpp
