######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 27 19:48:14 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
RESOURCES += jquery.qrc
