######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 30 16:44:08 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cannonfield.h gameboard.h lcdrange.h
SOURCES += cannonfield.cpp gameboard.cpp lcdrange.cpp main.cpp
